# NumPy Library  

NumPy (Numerical Python) is a fundamental library for numerical computing in Python.  
It provides efficient support for multi-dimensional arrays, mathematical functions, and optimized operations, making it a key tool in scientific computing, data science, and machine learning.  

## Key Features  
- 🚀 **High Performance** – Optimized for handling large arrays and matrices efficiently.  
- ⚡ **Vectorized Operations** – Eliminates the need for explicit loops, making computations faster.  
- 🔄 **Broadcasting** – Enables element-wise operations on arrays of different shapes.  
- 📊 **Comprehensive Mathematical Functions** – Supports linear algebra, statistical calculations, and complex number operations.  
- 🔗 **Seamless Integration** – Works well with other scientific computing libraries like SciPy, Pandas, and TensorFlow.  

## Installation  
To install NumPy, use the following command:  
```sh
pip install numpy


In [ ]:
import numpy as np
np.__version__

Yash Pandey


'2.2.4'

In [ ]:
# Creating a 1D NumPy array
numList=[1, 2, 3, 4]
arr = np.array(numList)  # NumPy arrays are more efficient than Python lists

# Element-wise operations
print(arr + 2)  # Adds 2 to each element: [3 4 5 6]
print(arr * 3)  # Multiplies each element by 3: [3 6 9 12]

[3 4 5 6]
[ 3  6  9 12]


In [7]:
# Creating a 2D array (Matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix

# Accessing elements
print(matrix[0, 1])  # Accesses element at row 0, column 1 (output: 2)
print(matrix.shape)  # (2, 3) - Rows x Columns
print(matrix.size)   # 6 - Total number of elements
print(matrix.ndim)   # 2 -> 2D Dimension Of the Matrix....

2
(2, 3)
6
2


In [8]:
# Another Way To Create Array Using np.asarray() & np.asanyarray().....
# `np.asarray()` converts input to a NumPy array without making a copy if it's already an array.......
#  while `np.asanyarray()` does the same but preserves subclasses like `np.matrix`.....
l=[1,2,3]
arr=np.asarray(l)
newarr=np.asanyarray(arr)
print(f"Th Dimension Of arr Is : {arr.ndim}") 
print(f"Th Dimension Of newarr Is : {newarr.ndim}") 

Th Dimension Of arr Is : 1
Th Dimension Of newarr Is : 1


### Shallow Copy vs. Deep Copy in NumPy  

```python
import numpy as np  

arr = np.array([1, 2, 3])  

shallow = arr.view()  # Shallow Copy (shares data)
deep = arr.copy()  # Deep Copy (independent copy)

shallow[0] = 100  
print(arr, deep)  # arr changes, deep remains same


NumPy Methods Demonstration:
- np.fromfunction(): Creates an array by executing a function over each coordinate.
- np.fromiter(): Creates an array from an iterable.
- np.arange(): Creates an array with a range of values.
- np.fromstring(): Creates an array from a string.
- np.linspace(): Creates an array with evenly spaced values.
- np.logspace(): Creates an array with logarithmically spaced values.

In [9]:
# np.fromfunction()
def func(x, y):
    return x + y
arr_func = np.fromfunction(func, (3, 3), dtype=int)
print("Array from function:")
print(arr_func)
print("Shape:", arr_func.shape)   # Returns the shape (dimensions) of an array.....
print("Size:", arr_func.size)     # Returns the total number of elements in an array....


Array from function:
[[0 1 2]
 [1 2 3]
 [2 3 4]]
Shape: (3, 3)
Size: 9


In [11]:
# np.fromiter()
iterable = range(1,5)
arr_iter = np.fromiter(iterable, dtype=int)
print("\nArray from iterable:", arr_iter)


Array from iterable: [1 2 3 4]


In [12]:
# np.arange()
arr_arange = np.arange(1, 10, 2)
print("\nArray from arange:", arr_arange)


Array from arange: [1 3 5 7 9]


In [13]:
# np.fromstring()
string_data = "1 2 3 4 5"
arr_string = np.fromstring(string_data, dtype=int, sep=' ')
print("\nArray from string:", arr_string)


Array from string: [1 2 3 4 5]


In [14]:
# np.linspace()
arr_linspace = np.linspace(1, 10, 5)
print("\nArray from linspace:", arr_linspace)


Array from linspace: [ 1.    3.25  5.5   7.75 10.  ]


In [15]:
# np.logspace()
arr_logspace = np.logspace(1, 3, 5)
print("\nArray from logspace:", arr_logspace)


Array from logspace: [  10.           31.6227766   100.          316.22776602 1000.        ]
