NumPy Methods Explanation:
- zeros(): Creates an array filled with zeros.
- ones(): Creates an array filled with ones.
- eye(): Creates an identity matrix.
- empty(): Creates an uninitialized array with random values.
- reshape(): Changes the shape of an array without altering its data.
- @ and np.dot(): Used for matrix multiplication.
- T (Transpose): Transposes rows and columns of a matrix.
- sqrt(): Computes the square root of each element in an array.
- log10(): Computes the base-10 logarithm of each element.
- exp(): Computes the exponential (e^x) of each element.
- min(), max(): Finds the minimum and maximum values in an array.
- np.random(): Generates random numbers.


In [1]:
import numpy as np

In [9]:
import numpy as np  

# Creating different types of arrays  
zero_array = np.zeros((3, 3))  # 3x3 array filled with zeros  
ones_array = np.ones((2, 2))  # 2x2 array filled with ones  
identity_matrix = np.eye(3)  # 3x3 Identity matrix  
empty_array = np.empty((2, 3))  # 2x3 uninitialized array (contains random values)  

In [10]:
# Reshaping an array  
reshaped_array = np.arange(6).reshape((2, 3))  # Reshaping a range of 6 elements into 2x3  
print("Reshaped Array:\n", reshaped_array)  


Reshaped Array:
 [[0 1 2]
 [3 4 5]]


In [11]:
# Matrix multiplication  
A = np.array([[1, 2], [3, 4]])  
B = np.array([[5, 6], [7, 8]])  
matmul_1 = A @ B  # Using '@' operator  
matmul_2 = np.dot(A, B)  # Using np.dot() function  

print("Matrix Multiplication (@ operator):\n", matmul_1)  
print("Matrix Multiplication (np.dot):\n", matmul_2)  

Matrix Multiplication (@ operator):
 [[19 22]
 [43 50]]
Matrix Multiplication (np.dot):
 [[19 22]
 [43 50]]


In [12]:
# Transpose of a matrix  
transposed_A = A.T  # Transposing matrix A  
print("Transposed Matrix A:\n", transposed_A)  

Transposed Matrix A:
 [[1 3]
 [2 4]]


In [14]:
# Mathematical operations  
sqrt_array = np.sqrt(np.array([4, 9, 16]))  # Square root of each element  
log_array = np.log10(np.array([10, 100, 1000]))  # Log base 10 of elements  
exp_array = np.exp(np.array([1, 2, 3]))  # Exponential of each element  

### np.random.rand(x , y)

- Generates a (x , y) Dimension matrix 
- All Elements Are filled with random floating-point numbers.
- The values are uniformly distributed in the range [0, 1) (excluding 1).

In [15]:
# Finding min and max values in a random array  
random_array = np.random.rand(3, 3)  # 3x3 array with random values  
min_value = random_array.min()  # Minimum value  
max_value = random_array.max()  # Maximum value  

print("Random Array:\n", random_array)  
print("Minimum Value:", min_value)  
print("Maximum Value:", max_value)  

Random Array:
 [[0.7104673  0.23013323 0.57094602]
 [0.62307144 0.4375271  0.64120023]
 [0.63235933 0.10082227 0.26677431]]
Minimum Value: 0.10082227431510982
Maximum Value: 0.7104673005677381


In [ ]:
# Array of 5 random values between 0 and 1  
random_numbers = np.random.rand(5)  

# Printing the array  
print("Random Numbers:\n", random_numbers)  

# Printing the min and max values  
print(f"The Min Value In The Linear Array Is : {random_numbers.min()}")  # Minimum value  
print(f"The Max Value In The Linear Array Is : {random_numbers.max()}")  # Maximum value  

Random Numbers:
 [0.2693754  0.18099279 0.05723473 0.83554192 0.6888865 ]
The Min Value In The Linear Array Is : 0.057234734392530795
The Max Value In The Linear Array Is : 0.835541915344409
