## NumPy Methods and Their Usage:

- flatten() - Converts a multi-dimensional array into a 1D array.
- expand_dims() - Expands the dimensions of an array, adding a new dimension.
- squeeze() - Removes single-dimensional entries from an array.
- repeat() - Repeats elements of an array along a specified axis.
- roll() - Rolls array elements along a given axis.
- where() - Returns indices where a condition is met.
- extract() - Extracts elements from an array based on a condition.
- byteswap() - Swaps the byte order of the array elements.
- Operations on NumPy String Array - Various operations like uppercase, lowercase, split, etc.
- Mathematical Operations in NumPy - Basic arithmetic operations on NumPy arrays.

In [2]:
import numpy as np

# Creating a sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
# 1. flatten()
flat_arr = arr.flatten()
print("Flattened Array:", flat_arr)

Flattened Array: [1 2 3 4 5 6]


In [4]:
# 2. expand_dims()
expanded_arr = np.expand_dims(arr, axis=0)
print("Expanded Array:\n", expanded_arr)

Expanded Array:
 [[[1 2 3]
  [4 5 6]]]


### np.expand_dims(newArr, axis=0) 
- Adds a new dimension at axis 0 (rows).
- Original Shape: (3, 3) → New Shape: (1, 3, 3)

### np.expand_dims(newArr, axis=1)
- Adds a new dimension at axis 1 (columns).
- Original Shape: (3, 3) → New Shape: (3, 1, 3)

In [ ]:
newArr=np.array([[1,2,3],[4,5,6],[7,8,9]])
expanded_arr = np.expand_dims(newArr, axis=0)
expanded_arr = np.expand_dims(newArr, axis=1)
expanded_arr

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [ ]:
# 3. squeeze() : 2D -> 1D
expanded_arr=np.array([[1],[4],[7]])
squeezed_arr = np.squeeze(expanded_arr)
print("Squeezed Array:", squeezed_arr)

Squeezed Array: [1 4 7]


### np.repeat(arr, num, axis)
- arr: Input NumPy array.
- num: Number of times each element should be repeated.
- axis: The axis for repeat (0 for rows, 1 for columns).

#### np.repeat(arr, 2, axis=0) -> Each row is repeated 2 times
#### np.repeat(arr, 2, axis=1) -> Each col is repeated 2 times

In [13]:
# 4. repeat()
arr = np.array([[1, 2, 3], [4, 5, 6]])
repeated_arr = np.repeat(arr, 3, axis=1)
print("Repeated Array:", repeated_arr)

Repeated Array: [[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


### np.roll(arr, shift, axis)
- arr: Input NumPy array.
- shift: Number of times each element should be shifted . 
- Positive values shift to the right, negative values shift to the left.
- axis: The axis for repeat (0 for rows, 1 for columns).

#### np.roll(arr, 2, axis=0) -> Each row element is been shifted 2 times
#### np.roll(arr, 2, axis=1) -> Each col element is been shifted 2 times

In [14]:
# 5. roll()
arr = np.array([[1, 2, 3], [4, 5, 6]])
rolled_arr = np.roll(arr, shift=1, axis=1)
print("Rolled Array:", rolled_arr)

Rolled Array: [[3 1 2]
 [6 4 5]]


In [15]:
# 6. where()
arr = np.array([[1, 2, 3], [4, 5, 6]])
condition = arr % 2 == 0
where_result = np.where(condition, "Even", "Odd")
print("Where Condition Result:", where_result)

Where Condition Result: [['Odd' 'Even' 'Odd']
 ['Even' 'Odd' 'Even']]


In [16]:
# 7. extract()
arr = np.array([[1, 2, 3], [4, 5, 6]])
extract_result = np.extract(condition, arr)
print("Extracted Even Numbers:", extract_result)

Extracted Even Numbers: [2 4 6]


Crux to Remember byteswap() 🔥
👉 It flips the byte order of each element in the array.

🛑 Think of it as reversing byte pairs

Little-endian (LSB first) → Big-endian (MSB first)

Big-endian (MSB first) → Little-endian (LSB first)

💡 Shortcut Rule: Small number becomes big, big number becomes small.

Example:

1 (0x0001) → 256 (0x0100)

256 (0x0100) → 1 (0x0001)

1024 (0x0400) → 4 (0x0004)

In [17]:
# 8. byteswap()
byte_swapped = arr.astype(np.int16).byteswap()
print("Byte-swapped Array:\n", byte_swapped)

Byte-swapped Array:
 [[ 256  512  768]
 [1024 1280 1536]]


In [18]:
# 9. Operations on NumPy String Array
str_arr = np.array(["hello", "world", "numpy"])
print("Uppercase:", np.char.upper(str_arr))
print("Lowercase:", np.char.lower(str_arr))
print("Title Case:", np.char.title(str_arr))
print("Split Example:", np.char.split(str_arr, "o"))

Uppercase: ['HELLO' 'WORLD' 'NUMPY']
Lowercase: ['hello' 'world' 'numpy']
Title Case: ['Hello' 'World' 'Numpy']
Split Example: [list(['hell', '']) list(['w', 'rld']) list(['numpy'])]


In [19]:
# 10. Mathematical Operations in NumPy
num_arr = np.array([1, 2, 3, 4])
print("Addition:", num_arr + 10)
print("Subtraction:", num_arr - 2)
print("Multiplication:", num_arr * 3)
print("Division:", num_arr / 2)
print("Exponentiation:", np.exp(num_arr))
print("Square Root:", np.sqrt(num_arr))

Addition: [11 12 13 14]
Subtraction: [-1  0  1  2]
Multiplication: [ 3  6  9 12]
Division: [0.5 1.  1.5 2. ]
Exponentiation: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Square Root: [1.         1.41421356 1.73205081 2.        ]
